#!/usr/bin/env python3
"""
tone-sweep.py - synthesise darker and dimmer variants of a captured frame.

WHAT THIS IS FOR
================
The tone tracker's weak spot is that its behaviour depends on the colouring and
the lighting of whoever is standing in front of it, and verifying that properly
needs a range of people. When you cannot assemble that, this gets you part of
the way: capture ONE real frame on the device, then generate a sweep of
variants that model what the same scene would look like with darker skin and
less light, and replay them through the real pipeline on the real hardware.

    on the device : press CAPTURE with a hand in frame
    adb pull /sdcard/theremin/testframes/cap-001.nv21
    python scripts/tone-sweep.py cap-001.nv21 --out sweep/
    adb push sweep/*.nv21 /sdcard/theremin/testframes/
    on the device : switch to Tone, press REPLAY, watch the quality line

WHAT IT PROVES, AND WHAT IT DOES NOT
====================================
It proves that the adaptive tolerance actually widens enough to hold a match as
luminance falls, and it shows you WHERE that breaks. That is a real, repeatable
answer to a real question, and it is the failure mode we were most worried
about.

It does NOT prove the app works for people with darker skin. This is a model.
Real skin differs from a transformed image in ways this does not capture:
melanin changes spectral reflectance rather than simply scaling brightness,
real camera auto-exposure responds to the whole scene, and a real capture has
noise generated by the sensor rather than added afterwards.

Treat a pass here as "the obvious failure is absent", not as validation. The
acceptance gate in SPEC.md stays open until somebody runs it with people.

THE MODEL
=========
Three effects, in the order they matter:

1. LUMINANCE. The dominant effect. Melanin absorbs light, so less comes back.
   Y is scaled by a factor.

2. NOISE. The one that actually breaks the tracker, and the one a naive recolour
   forgets. Photon shot noise means the signal-to-noise ratio scales with the
   square root of the signal, so a subject reflecting a quarter of the light has
   roughly half the SNR. Scaling Y down WITHOUT adding noise produces an
   unrealistically clean dark image and a falsely reassuring result. Noise is
   added to the chroma plane in particular, because chroma is already subsampled
   2x2 and is what the tone tracker reads.

3. CHROMA SHIFT. Real but modest. Darker skin tends to sit slightly differently
   on the chroma plane rather than somewhere else entirely, which is exactly why
   chroma-based matching is used at all. Applied as a small configurable nudge;
   the default is deliberately conservative because overstating it would make
   the test easier, not harder.

4. AUTO-EXPOSURE (optional, --ae). What a real camera would do: brighten the
   frame back up. That recovers the apparent brightness and amplifies the noise
   with it, which is why underexposed-then-corrected footage looks grainy. This
   is closer to what the hardware really produces, so it is worth running both
   ways.

No third-party libraries: this reads and writes raw NV21 and uses only the
standard library, so it runs anywhere Python does.
"""

import argparse
import math
import os
import random
import struct
import sys

WIDTH = 320
HEIGHT = 240
Y_SIZE = WIDTH * HEIGHT
UV_SIZE = Y_SIZE // 2
FRAME_SIZE = Y_SIZE + UV_SIZE


def clamp(v, lo=0, hi=255):
    return lo if v < lo else (hi if v > hi else int(v))


def load(path):
    with open(path, 'rb') as f:
        data = bytearray(f.read())
    if len(data) < FRAME_SIZE:
        sys.exit("%s is %d bytes; expected %d for %dx%d NV21"
                 % (path, len(data), FRAME_SIZE, WIDTH, HEIGHT))
    return data[:FRAME_SIZE]


def stats(frame):
    """Mean luma and mean chroma, for the report."""
    y = sum(frame[:Y_SIZE]) / float(Y_SIZE)
    cr = sum(frame[Y_SIZE::2]) / float(UV_SIZE // 2)
    cb = sum(frame[Y_SIZE + 1::2]) / float(UV_SIZE // 2)
    return y, cb, cr


def transform(src, y_scale, cb_shift, cr_shift, noise_gain, ae, rng):
    """
    Produce one variant.

    y_scale     0..1, fraction of light coming back
    cb_shift    chroma nudge, in Cb units
    cr_shift    chroma nudge, in Cr units
    noise_gain  multiplier on the modelled shot noise
    ae          simulate auto-exposure correcting the exposure back up
    """
    out = bytearray(src)

    # Shot noise scales with the square root of the signal, so the RELATIVE
    # noise grows as 1/sqrt(scale). This is the term that makes the test
    # honest; without it a dark frame is unrealistically clean.
    snr_penalty = 1.0 / math.sqrt(max(y_scale, 0.01))
    y_sigma = 1.4 * snr_penalty * noise_gain
    # Chroma gets hit harder: it is subsampled 2x2, so each stored sample is
    # already an average of fewer photons, and any later processing amplifies
    # what is left.
    c_sigma = 2.2 * snr_penalty * noise_gain

    ae_gain = (1.0 / y_scale) if ae else 1.0
    # Auto-exposure amplifies the noise along with the signal - that is why
    # brightened footage looks grainy rather than clean.
    if ae:
        y_sigma *= ae_gain
        c_sigma *= ae_gain

    # --- luma plane ---
    for i in range(Y_SIZE):
        v = src[i] * y_scale * ae_gain + rng.gauss(0.0, y_sigma)
        out[i] = clamp(v)

    # --- chroma plane, interleaved V,U ---
    for i in range(Y_SIZE, FRAME_SIZE, 2):
        v = src[i] - 128.0      # Cr, centred
        u = src[i + 1] - 128.0  # Cb, centred
        # Lower luminance compresses chroma toward neutral: less light means
        # less colour information survives, which is a real effect and not
        # merely noise.
        compress = 0.75 + 0.25 * y_scale
        v = v * compress + cr_shift + rng.gauss(0.0, c_sigma)
        u = u * compress + cb_shift + rng.gauss(0.0, c_sigma)
        out[i] = clamp(v + 128.0)
        out[i + 1] = clamp(u + 128.0)

    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('source', help='a captured .nv21 frame (320x240)')
    ap.add_argument('--out', default='sweep', help='output directory')
    ap.add_argument('--steps', type=int, default=6,
                    help='number of variants across the range (default 6)')
    ap.add_argument('--min-scale', type=float, default=0.30,
                    help='darkest variant, as a fraction of the original light '
                         '(default 0.30)')
    ap.add_argument('--cb-shift', type=float, default=-2.0,
                    help='Cb nudge at the darkest step (default -2, conservative)')
    ap.add_argument('--cr-shift', type=float, default=3.0,
                    help='Cr nudge at the darkest step (default +3, conservative)')
    ap.add_argument('--noise', type=float, default=1.0,
                    help='multiplier on modelled shot noise (default 1.0)')
    ap.add_argument('--ae', action='store_true',
                    help='simulate auto-exposure brightening the frame back up, '
                         'which amplifies the noise with it')
    ap.add_argument('--seed', type=int, default=1,
                    help='RNG seed, so a sweep is reproducible (default 1)')
    args = ap.parse_args()

    src = load(args.source)
    rng = random.Random(args.seed)

    if not os.path.isdir(args.out):
        os.makedirs(args.out)

    base = os.path.splitext(os.path.basename(args.source))[0]
    y0, cb0, cr0 = stats(src)

    print("source %s: mean Y %.1f, Cb %.1f, Cr %.1f" % (args.source, y0, cb0, cr0))
    print("auto-exposure simulation: %s" % ("ON" if args.ae else "off"))
    print()
    print("%-28s %7s %7s %7s %7s" % ("file", "scale", "meanY", "meanCb", "meanCr"))
    print("-" * 62)

    for i in range(args.steps):
        # Step 0 is the original, untouched, so the sweep contains its own
        # control. Without it you cannot tell a tracker failure from a frame
        # that was never trackable to begin with.
        t = i / float(max(args.steps - 1, 1))
        scale = 1.0 - t * (1.0 - args.min_scale)

        if i == 0:
            out = bytearray(src)
        else:
            out = transform(src, scale, args.cb_shift * t, args.cr_shift * t,
                            args.noise, args.ae, rng)

        name = "%s-tone%02d.nv21" % (base, i)
        path = os.path.join(args.out, name)
        with open(path, 'wb') as f:
            f.write(out)

        y, cb, cr = stats(out)
        print("%-28s %7.2f %7.1f %7.1f %7.1f" % (name, scale, y, cb, cr))

    print()
    print("Wrote %d frames to %s/" % (args.steps, args.out))
    print()
    print("Next:")
    print("  adb push %s/*.nv21 /sdcard/theremin/testframes/" % args.out)
    print("  On the device: switch to Tone, calibrate on step 00, press REPLAY.")
    print()
    print("What to watch: the quality line. Margin should stay above 0.25 as the")
    print("frames darken. Where it drops, that is where the adaptive tolerance")
    print("stops keeping up - and that number is the useful output of this test.")
    print()
    print("Remember this is a model, not a validation. See the header, and the")
    print("acceptance gate in SPEC.md.")


if __name__ == '__main__':
    main()
